[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/nix/store/h3l6c14c5ckdgcw6fcwz47ni7cc5jmi3-mold-1.4.2/bin/mold"]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"